- src/bin/add/args.rs
- src/bin/add/main.rs
- src/bin/list/list.rs
- src/bin/list/main.rs
- src/bin/list/tree.rs
- src/manifest.rs
It's a small change, but makes the code cleaner.
AFAIK `&String` is strictly inferior to `&str`; it's less flexible, for no real benefits.
[`clippy` even warns against &String](https://github.com/Manishearth/rust-clippy/wiki#ptr_arg).
> use &str instead of &String everywhere

- Cargo.lock
- Cargo.toml
- README.md
- src/bin/add/args.rs
- src/bin/add/fetch_version.rs
- src/bin/add/main.rs
- src/bin/list/main.rs
- src/bin/list/tree.rs
- tests/cargo-add.rs
This introduces two new dependencies, _curl_ and _quick-error_. I'm using _curl_ (and not _hyper_) because I initially wanted to use the [_crates-io_](https://crates.io/crates/crates-io) crate. Sadly, it does not expose the get/req methods.
This fixes #12.
> Fetch Latest Version Number from Crates.io!

- Cargo.lock
- Cargo.toml
- src/bin/add/fetch_version.rs
- src/bin/add/main.rs
- src/bin/list/main.rs
- src/bin/rm/main.rs
- src/manifest.rs
- tests/cargo-add.rs
- tests/cargo-list.rs
- tests/cargo-rm.rs
- tests/fixtures/rm/Cargo.toml
- tests/utils.rs
I added a few integration tests for basic stuff (invalid/no args) as well es more special ones for the nice error messages of `cargo rm`. Along the way, I also changed the binaries to log error to `stderr`.
Thanks for the good basis, @MrJohz!
> Add More Integration Tests

- src/bin/list/main.rs
It seems the --manifest-path help text was copied from the cargo-add
command.
> Fix help text of cargo-list

- src/bin/add/args.rs
- src/bin/add/main.rs
- tests/cargo-add.rs
Also expands the CLI docs a bit.
cf. #43
> `cargo add` Now Uses `--vers` Instead of `--ver`

- src/manifest.rs
- tests/cargo-rm.rs
This also adds another assert to the doctest, a unit test in src/manifest.rs, and an integration test in tests/cargo-rm.rs
This is checklist item 5 as part of #28.
I'd love suggestions on how to do this better:
```rust
if let Some(b) = section.get().as_table().and_then(|x| Some(x.is_empty())) {
if b {
section.remove();
}
};
```
> Remove manifest section after its last dependency has been removed

- tests/cargo-rm.rs
- tests/fixtures/rm/Cargo.toml
This adds `remove_existing_dependency` and
`remove_existing_dependency_from_specific_section` to test removing
dependencies from arbitrary, build, and dev sections.
This also modifies the Cargo.toml fixture to add a build section to test
removing from this section.
> Add tests for removing existing dependencies

- src/bin/list/list.rs
- src/bin/list/list_error.rs
- src/bin/list/main.rs
- src/bin/list/tree.rs
- src/bin/rm/args.rs
- src/manifest.rs
- tests/cargo-list.rs
- tests/fixtures/list/Cargo.toml
Like described in #50, this changes `cargo list` to be more strict in what it can show.
I also added support for showing git repo URLs and paths. ~~I'll see if I can easily add "optional" markers.~~ <ins>Yep.</ins>
> Refactor `cargo list` (cf. #50)

- src/bin/list/list.rs
- src/bin/list/main.rs
This allows you to execute cargo list for a crate that does not have any
dependencies. A downside of this approach is that you don't get an error
anymore if you misspell the section name.
Sample `Cargo.toml` that it rejected before:
[package]
name = "name"
version = "0.0.1"
authors = ["Author Name <author@example.com>"]
> Treat missing sections as empty, not as error

- src/bin/list/list.rs
- src/bin/list/main.rs
- tests/cargo-list.rs
- tests/fixtures/list-empty/Cargo.toml
Based on @tbu-'s #42. This just adds integration tests for `cargo list`.
> `cargo list` missing sections as empty

- Cargo.toml
The previous version didn't work because it was invalidly packaged
by cargo.
> Bump Version to 0.1.2

- Cargo.lock
- Cargo.toml
- src/bin/add/args.rs
- src/bin/add/fetch_version.rs
- src/bin/add/main.rs
- tests/cargo-add.rs
I've been talking about this with @jplatte on IRC for a while.
We still need to add some tests for this. E.g.:
Concerns #59
> Multiple crates

- src/manifest.rs
- tests/fixtures/manifest-invalid/Cargo.toml.sample
- tests/test_manifest.rs
When the input TOML file can not be parsed the file position (line, column) of the last parse error is printed with the error message. The formatting of the file position is the same as in cargo itself (but missing the file name currently).
I was not sure where to place the new test. Since it's the first test for code in manifest.rs I created a new test_manifest.rs.
Disclaimer: This is my first PR ever and also I'm a complete Rust noob. I hope this is useful somehow anyway.
> Output error position on TOML parse error

- src/bin/add/args.rs
- src/bin/add/fetch.rs
- src/dependency.rs
- tests/cargo-add.rs
> Add the correct crate name (as in crates.io) to toml and notify user

- src/bin/add/args.rs
- src/bin/add/fetch.rs
- src/bin/add/main.rs
- src/bin/list/list.rs
- src/bin/list/main.rs
- src/bin/list/tree.rs
- src/bin/rm/main.rs
- src/dependency.rs
- src/manifest.rs
- tests/cargo-add.rs
- tests/utils.rs
This is a rollup of #98 (which replaces #78), #99, and #100. 
@sebasgarcep and @sinkuu, thank you for your PRs! Do you have time to review this? I've add a few tests and changed to code slightly, before running Rustfmt and Clippy.
Just to make sure Github gets all the references:
Fixes #52
Fixes #88
Fixes #92
> New year, new bugfixes

- src/bin/add/args.rs
- src/bin/add/fetch.rs
- src/bin/add/main.rs
Solves #96. Passes all tests and adds a couple to test the new features. Updates the version fetcher algorithm to ignore prerelease versions unless the --fetch-prereleases flag is passed to it.
@killercup Any suggestions/changes?
> Fetch non-prerelease versions

- src/bin/add/args.rs
- src/bin/add/main.rs
- src/manifest.rs
- tests/cargo-add.rs
This adds the specified dependency/ies only if they are already present. Thus, it acts like a 'cargo upgrade' (see #74).
This PR is a partial solution to the problem of updating dependencies in `Cargo.toml` for crates in a workspace that do not share the same set of dependencies. Once this has been merged, one will then be able to upgrade the dependency `foo` for all crates by running `cargo multi add --update-only foo` (using [cargo-multi](https://crates.io/crates/cargo-multi)).
> Add `--update-only` flag to cargo-add

- .travis.yml
- src/bin/add/args.rs
- src/bin/add/fetch.rs
- src/bin/add/main.rs
- src/bin/list/tree.rs
- tests/cargo-add.rs
- tests/utils.rs
See #121.
This enables clippy for `nightly-2017-06-25` and fixes most of the clippy warnings.
> Enable clippy properly and fix non-spurious warnings

- src/bin/list/list.rs
Hi @killercup 
The changes are self-descriptive I think :)
> Remove redundant space if output does not contain a version.

- Cargo.lock
- Cargo.toml
- Makefile
- src/bin/add/args.rs
- src/bin/add/fetch.rs
- src/bin/add/main.rs
- src/bin/list/list.rs
- src/bin/list/main.rs
- src/bin/list/tree.rs
- src/bin/rm/main.rs
- src/manifest.rs
Sorry, my commits were squashed during stashing.
- curl is replaced with reqwest
- added structs instead of json::Value
- try! is replaced with ?
> Modernize all the things

- Cargo.toml
- src/bin/add/args.rs
- src/bin/add/fetch.rs
- src/bin/add/main.rs
- src/bin/rm/main.rs
- src/dependency.rs
- src/manifest.rs
- tests/cargo-add.rs
- tests/cargo-rm.rs
- tests/utils.rs
The reasoning is simple: Running cargo-add and rustfmt will currently cause this diff. If you do that now, we can freely use these tools in the future without a huge mess.
> Standardize style

- Cargo.toml
- README.md
- appveyor.yml
Reprise of #49 - it seems to work again now ([![Build status](https://ci.appveyor.com/api/projects/status/rba5ffptnj78o4xm?svg=true)](https://ci.appveyor.com/project/bjgill/cargo-edit)).
Fixes #55
> Add Appveyor Config for Windows CI

- appveyor.yml
- bors.toml
Forgot to mention in pull #135.
bors r? @bjgill
> Tell bors-ng about appveyor

- Cargo.lock
- Cargo.toml
- README.md
- src/bin/add/args.rs
- src/bin/add/fetch.rs
- src/bin/add/main.rs
- src/bin/rm/main.rs
- src/dependency.rs
- src/manifest.rs
- tests/cargo-add.rs
Now, if we attempt to add a dependency that already exists, we will not
throw away information. i.e. an optional dependency will always remain
as such.
Also some minor refactoring to use PathBuf instead of String where
appropriate.
This is a necessary prerequisite for a follow-on PR that implements a `cargo upgrade`
> Properly support updating dependencies

- .travis.yml
- Cargo.lock
- src/bin/add/main.rs
- src/bin/rm/main.rs
- src/bin/upgrade/main.rs
- src/lib.rs
The clippy update is boring - nothing exciting happened.
Rustfmt is more interesting. This PR checks that rusfmt thinks the code is all properly formatted. An unfortunate side-effect is that we are now pinned to a specific version of rustfmt. This will prevent spontaneous breakages when rustfmt next updates, though, so it's probably acceptable...
Inspired by #146
> Use latest rustfmt-nightly and clippy in travis

- CONTRIBUTING.md
- README.md
Adds a contribution guide to the readme as per #146.
Also removes the non-`cargo install` installation instructions - `cargo` is now sufficiently mature that everyone should be using it.
> Add contribution guide (and remove non-cargo install instructions)

- .travis.yml
Follow-up from #148. This should catch any future issues where
Cargo.lock is not up to date.
> Check that `cargo test` leaves files unchanged

- Cargo.lock
- Cargo.toml
- src/lib.rs
- src/manifest.rs
- tests/cargo-upgrade.rs
When the version of a dependency, cargo-upgrade now outputs "Upgrading
crate vOld -> vNew" with the same text style as `cargo update`.
> Add an output for `cargo upgrade`

- Cargo.lock
- Cargo.toml
- README.md
- src/bin/upgrade/main.rs
- src/lib.rs
- src/manifest.rs
- tests/cargo-upgrade.rs
- tests/fixtures/upgrade/Cargo.toml.invalid
- tests/fixtures/workspace/Cargo.toml
- tests/fixtures/workspace/explicit/four/Cargo.toml
- tests/fixtures/workspace/implicit/three/Cargo.toml
- tests/fixtures/workspace/one/Cargo.toml
- tests/fixtures/workspace/two/Cargo.toml
- tests/utils.rs
`cargo upgrade --all` uses `cargo metadata` to discover the workspace members, and then runs over all members of the workspace.
Note that we just run though each workspace member in turn. This means that we are likely to be doing dependency resolution multiple times. This is probably acceptable for an initial release, but a better long-term solution would implement caching so as to only look up each dependency once.
This is the first stage of resolving #147
> Add basic workspace support – `cargo upgrade --all`

- Cargo.toml
- README.md
Fixes #152. Done using features.
Testing this from my working copy:
```
$ cargo install -f --no-default-features --features "add upgrade"
Installing cargo-edit v0.2.0 (file:///home/benjamin/rust/cargo-edit)
Compiling cargo-edit v0.2.0 (file:///home/benjamin/rust/cargo-edit)
Finished release [optimized] target(s) in 13.64 secs
Replacing /home/benjamin/.cargo/bin/cargo-add
Replacing /home/benjamin/.cargo/bin/cargo-upgrade
```
> Support selecting which binaries to install

- appveyor.yml
- bors.toml
With `appveyor-retry` so we hopefully have fewer failures due to spurious network failures in future.
Fixes #139
> Add appveyor back into bors

- Cargo.lock
- Cargo.toml
- src/bin/add/args.rs
- src/bin/add/main.rs
- src/bin/rm/main.rs
- src/bin/upgrade/main.rs
- src/errors.rs
- src/fetch.rs
- src/lib.rs
- src/manifest.rs
- tests/cargo-add.rs
- tests/cargo-rm.rs
- tests/cargo-upgrade.rs
- tests/test_manifest.rs
- tests/utils.rs
I've kept the quick-error style errors where they're used multiple times, and otherwise converted to string errors - our errors are for diagnostics only (not for anyone to try and do anything with).
This is the first step to solving #159.
> Switch to use error-chain

- Cargo.lock
As discussed on IRC, this `Cargo.lock` works with newer LibreSSL, because it doesn't pin `openssl-sys` on an older version.
> Updated lockfile to compile with newer LibreSSL.

- Cargo.lock
- tests/cargo-add.rs
The crate `failure` has just been published. We need a sillier name that has less chance of becoming a real crate in future.
> Be more cautious with bogus crate naming

- .travis.yml
- src/bin/add/args.rs
- src/bin/add/main.rs
- src/bin/rm/main.rs
- src/bin/upgrade/main.rs
- src/fetch.rs
- src/lib.rs
- src/manifest.rs
- tests/cargo-add.rs
- tests/cargo-upgrade.rs
Now that we use cargo_metadata, we no longer need to be able to parse
the lock file.
Also, update to the latest releases of rustfmt and clippy
> Remove unused Cargo.lock search handling

- src/errors.rs
- src/manifest.rs
- tests/cargo-upgrade.rs
We now provide a similar error message to `Cargo`.
It would be nice to have context-specific information depending on whether this is being called from `upgrade`, which supports `--all` or `add`/`rm`, which don't. However, this is probably good enough for now.
Solves #157
> Detect when running against a virtual manifest

- Cargo.lock
- Cargo.toml
Contains these PRs: https://github.com/killercup/cargo-edit/pulls?utf8=✓&q=merged%3A2017-08-16..2017-12-19
> Bump version to 0.3.0-beta.1

- Cargo.lock
- Cargo.toml
- README.md
- src/bin/add/args.rs
- src/bin/add/main.rs
- src/bin/rm/args.rs
- src/bin/rm/main.rs
- src/bin/upgrade/main.rs
- tests/cargo-add.rs
- tests/cargo-rm.rs
fixes #189 .
With this PR, `cargo add` and `cargo rm` print short messages to let the user know what they're doing.
> Stdout messages

- tests/cargo-add.rs
- tests/cargo-rm.rs
The tests I added for the newly merged stdout messages are flawed.
Because of how assert_cli 0.4 works, putting several `.prints()` calls on a single Assertion will only evaluate the one added last. Therefore, my tests can succeed even if there is very different stdout output in the beginning.
Luckily, since colored output is disabled in tests, we can instead use `prints_exactly()` and assert the entire output. This PR does that.
In order to be able to assert the full output, the tests now also ask for a specific version of the crates they're adding.
> fix tests for stdout messages of cargo add/rm

- README.md
- src/bin/upgrade/main.rs
Not everyone automatically knows what a manifest is.
Solves #195.
> Explicitly mention `Cargo.toml`

- .travis.yml
- src/bin/add/args.rs
- src/bin/rm/main.rs
- src/bin/upgrade/main.rs
- tests/cargo-add.rs
- tests/cargo-upgrade.rs
Use the latest version of nightly clippy (0.0.186) - no new warnings. Also switch to the stable train of rustfmt previews.
> Upgrade Rustfmt + clippy

- Cargo.lock
- Cargo.toml
- README.md
- src/bin/add/args.rs
- src/bin/upgrade/main.rs
- src/crate_name.rs
- src/lib.rs
- src/manifest.rs
- tests/cargo-add.rs
- tests/cargo-upgrade.rs
- tests/fixtures/add/Cargo.toml.sample
- tests/fixtures/upgrade/Cargo.toml.source
- tests/fixtures/upgrade/Cargo.toml.target
- tests/utils.rs
Fixes #177. If this flag is provided, all dependencies upgraded will be blindly upgraded to the
version specified. Added a test for this new feature.
Also, there has been substantial refactoring. The new `Manifests` and `Dependencies` structs now
hold the logic for upgrade. This allows us to commonise the cases of a single and full
workspace upgrade quite considerably.
EDIT: this also fixes #182 (I'll open a new issue for alternate registries)
> Add `--precise` flag for cargo-upgrade 

- src/bin/upgrade/main.rs
- src/manifest.rs
A simple change to get `cargo-upgrade` to print the name of the package we're about to upgrade.
> cargo-upgrade prints manifests

- .travis.yml
This should fix broken ci [builds](https://travis-ci.org/killercup/cargo-edit/jobs/407041576#L507).
> ci: update and fix clippy installation

- Cargo.lock
- Cargo.toml
Those need to be update together otherwise error-chain gets a 0.11
dependency injected and causes build error due conflicting types.
Signed-off-by: Otavio Salvador <otavio@ossystems.com.br>
> Update error-chain and cargo_metadata

- Cargo.toml
- src/bin/add/args.rs
- src/bin/add/main.rs
- src/bin/rm/args.rs
- src/bin/rm/main.rs
- src/bin/upgrade/main.rs
- src/crate_name.rs
- src/errors.rs
- src/fetch.rs
- src/lib.rs
- src/manifest.rs
- tests/cargo-add.rs
- tests/cargo-rm.rs
- tests/cargo-upgrade.rs
- tests/test_manifest.rs
- tests/utils.rs
There was function `get_with_timeout`, re-create a client each time this function is called, and "timeout" always 'default', I merged these two functions and reuse reqwest::Client to reuse TCP connection.
Other mirror change:
+ move to 2018 edition
+ work with rustfmt
Recommended review way: commit by commit.
> Migrate to 2018 edition

- src/bin/upgrade/main.rs
> [upgrade] `all` doens't conflict with `dependency`

- Cargo.lock
- Cargo.toml
https://github.com/killercup/cargo-edit/releases/tag/v0.3.2
> [Cargo.toml] bump version to 0.3.2

- tests/cargo-upgrade.rs
Flag one more test as requiring external APIs
> Flag one more test as requiring external APIs

- Cargo.lock
- Cargo.toml
- src/bin/upgrade/main.rs
- src/lib.rs
resolve #307
Updated cargo_metadata from 0.6 to 0.8.
The major changes from the update are:
1. Since the error management crate was changed from error-chain to failure, the error handling point was corrected.
2. Metadata acquisition processing was changed from metadata function to MetadataCommand :: exec.
> upgrade cargo_metadata to 0.8.0

- tests/cargo-add.rs
- tests/cargo-rm.rs
- tests/cargo-upgrade.rs
- tests/test_manifest.rs
- tests/utils.rs
I set `CARGO_TARGET_DIR` locally (as well as on newer CI setups) so this
was required to make tests pass for me.
> Abstract over finding binaries in tests

- Cargo.lock
- Cargo.toml
- src/manifest.rs
uses toml_edit from this PR: https://github.com/ordian/toml_edit/pull/63
solves https://github.com/killercup/cargo-edit/issues/218 pretty convincingly 
previously it was:
> 1457 (2%) also did something else (mostly moving sections of the file around, but ~10 also made whitespace changes, like removing spaces from section headers)
Now it is:
> 13 (0.02%) also did something else (mostly removing whitespace from section headers but a handful also fixed unix/windows line endings that I failed to clean up properly before starting).
> Use toml_edit's to_string_in_original_order()

- Cargo.lock
- Cargo.toml
- src/bin/add/args.rs
- src/bin/add/main.rs
- src/bin/upgrade/main.rs
- src/dependency.rs
- src/errors.rs
- src/fetch.rs
- src/lib.rs
- src/registry.rs
- tests/cargo-add.rs
- tests/cargo-upgrade.rs
- tests/fixtures/alt-registry-cargo-config
- tests/fixtures/upgrade/Cargo.toml.alt_registry
- tests/utils.rs
This PR adds support for alternative registries.
The main change is updating the `fetch::get_latest_dependency` to optionally accept a registry URL. I'm using URLs not registry names, because `cargo metadata` returns the URL of the index whenever the dependency is being sourced from an alternative registry.
When adding dependencies from alternative registries, the user specifies a registry name which is then converted to the relevant URL. For this purpose, the cargo config parsing code in `registry.rs` is updated to handle registries other than crates-io.
W.r.t testing, I've only added tests for the CLI/toml-editing aspects. I've been successfully using `cargo upgrade` with my company's alternative registry, but I've not added tests that actually query an alternative registry, because the …
> alternative registry support

- Cargo.lock
Fixes this `warning: package `miniz_oxide v0.3.4` in Cargo.lock is yanked in registry `crates.io`, consider updating to a version that is not yanked`.
```
❯ cargo tree -i -p miniz_oxide   
miniz_oxide v0.3.4                                                                                                                                                                                                  
└── flate2 v1.0.12
└── reqwest v0.9.22
```
> cargo update -p miniz_oxide

- tests/cargo-add.rs
- tests/fixtures/upgrade/Cargo.toml.source
- tests/fixtures/upgrade/Cargo.toml.target
This was a documentation bug https://github.com/rust-lang/cargo/issues/7613#issuecomment-557150300.
Fixes CI failures on beta and nightly channels.
> tests: slash is not valid

- README.md
- src/bin/add/args.rs
This patch updates the help output of the cargo add, cargo rm and cargo
upgrade commands in the readme file as some new options (--offline,
--skip-compatible) were missing.
As the format of the help output has changed since the last update of
the readme, the complete output is replaced.
> Update help output in readme file

- src/bin/add/args.rs
- src/crate_name.rs
- src/dependency.rs
- tests/cargo-add.rs
This provides the minimal changes necessary to support the `branch` argument in a `Cargo.toml` dependency. `cargo-add` now accepts `--branch xyz` which when used in concert with `--git` produces
```Toml
my_crate = { git = "https://github.com/my-org/my-crate", branch = "xyz" }
```
A provisional unit test is provided which ensures the branch is present if specified and not present in the original git repo test.
> Dependency support for git branches

- Cargo.lock
- Cargo.toml
- tests/cargo-upgrade.rs
- tests/utils.rs
The tempdir crate, a dev-dependency needed for the tests, has been
deprecated in favor of tempfile.  This patch replaces tempdir 0.3.7 with
tempfile 3.1.0.
Note that this patch also removes the prefixes from the temporary
directories: They are no longer required by the API, and they are not
needed for the tests.
----
I wrote this patch for the Debian package as the deprecated tempdir
crate will not be packaged for Debian.  But I think it would make sense
to also replace the dependency upstream.
> tests: Replace tempdir with tempfile

- src/manifest.rs
- tests/cargo-add.rs
- tests/cargo-upgrade.rs
This PR clippy warnings found at:
https://github.com/killercup/cargo-edit/runs/417584635?check_suite_focus=true
and several Windows errors found at:
https://github.com/killercup/cargo-edit/runs/417584722?check_suite_focus=true
I confirmed all warnings and errors except for one were fixed on my fork repository:
https://github.com/rhysd/cargo-edit/actions/runs/35804962
1 error is remaining on Windows node. But I could not find the reason since it was not reproducible on my local Windows machine. This PR does not fix it.
```
failures:
---- invalid_manifest stdout ----
thread 'invalid_manifest' panicked at 'Assertion failed for `D:\a\cargo-edit\cargo-edit\target\debug\cargo-upgrade upgrade --manifest-path C:\Users\RUNNER~1\AppData\Local\Temp\.tmpl9pxgX\Cargo.toml`
with: Unexpected stderr …
```
> Fix clippy warnings and some errors on Windows

- src/bin/add/args.rs
- src/bin/add/main.rs
- src/bin/rm/main.rs
- src/bin/upgrade/main.rs
- src/errors.rs
- src/lib.rs
- src/metadata.rs
- tests/cargo-add.rs
- tests/cargo-rm.rs
- tests/cargo-upgrade.rs
- tests/utils.rs
> Add `--package <pkgid>` to all commands

- README.md
- src/bin/add/args.rs
- src/bin/add/main.rs
- src/bin/upgrade/main.rs
- src/dependency.rs
- src/fetch.rs
- src/metadata.rs
- tests/cargo-add.rs
- tests/cargo-upgrade.rs
About 15% of all Cargo.toml files that I found in the wild contain something of the form `features = [...`, so I think that this is something that `cargo add` should be able to support somehow.
I agree with everyone that `cargo feature` is a really excellent idea, and provides a really good user experience @Riey has done a really good job. Allowing users to specify features in a single `cargo add` command is also valuable though, because it allows library authors to provide copy-pastable quick-start instructions.
To address some of the recent comments on https://github.com/killercup/cargo-edit/issues/193: when picking syntax for specifying features with `cargo add`, I would err on the side of having a more explicit, verbose syntax, because people will inevitably be pasting `cargo add` …
> "Working with features" updated

- src/bin/upgrade/main.rs
- src/metadata.rs
- tests/cargo-upgrade.rs
I have physically removed, so to speak, the usage of deprecated `--all` flag, and replaced it with entropic cylinders.
Namely, in the message when running `upgrade` in workspace root, in all tests other than the deprecation message test, and in the test for the aforementioned message.
> Replace use and suggestion of deprecated `--all`

- src/errors.rs
- src/fetch.rs
Fixes #411
TODO: Is it ok if we take the first one we find. Are there any examples
of having more than one file in `refs/remotes/origin/`?.
> Fix to allow any remote name to be used

- README.md
- src/bin/add/args.rs
- src/bin/add/main.rs
- tests/cargo-add.rs
- tests/fixtures/add/Cargo.toml.sorted
This should avoid the need to pass the `-s` option, except to sort
dependencies that are currently unsorted. Adjust the documentation of
that option accordingly.
> Keep dependencies in sorted order if they were already sorted

- src/bin/add/args.rs
- src/bin/add/main.rs
- src/bin/upgrade/main.rs
- src/crate_name.rs
- src/dependency.rs
- src/fetch.rs
- src/manifest.rs
This PR fixes all warnings from `cargo clippy` and `cargo fmt -- --check`.
> Fix all clippy warnings

- .gitattributes
- tests/cargo-add.rs
This should fix CI errors of this form on windows:
with: Unexpected stderr
with: Didn't match.
diff=
...
-6 | key = invalid-value
+6 | key = invalid-value
...
Git defaults to setting autocrlf to true. If you want to override
this for CI, one suggested approach is to use gitattributes.
See here for details:
https://github.community/t5/GitHub-Actions/git-config-core-autocrlf-should-default-to-false/td-p/30445
(Thanks to @frigus02 for helping me test this out on Windows, and pointing me to the above link)
> Disable autocrlf for Cargo.toml fixtures

- .travis.yml
`.travis.yml` uses `before_script` for running litners. However, `before_script` ignores non-zero exit status. From https://docs.travis-ci.com/user/job-lifecycle/#breaking-the-build,
> The exit code of after_success, after_failure, after_script, after_deploy and subsequent stages do not affect the build result. However, if one of these stages times out, the build is marked as failed.
This is why linter failures (#422) was overlooked. Travis CI ran linters but did not report the failure.
While confirming the result, I mark this PR as draft.
> Use before_script instead of after_script for linter checks on Travis CI

- src/bin/upgrade/main.rs
- tests/fixtures/upgrade/Cargo.toml.lockfile_source
- tests/fixtures/upgrade/Cargo.toml.lockfile_target
Previously `cargo upgrade --to-lockfile` does not update optional dependencies that are not enabled by default because `cargo metadata` only enables the `default` feature and does not report these dependencies. This PR changes `cargo upgrade --to-lockfile` to pass `--all-features` to `cargo metadata`, so it will report them and `cargo upgrade --to-lockfile` will update them.
> Pass --all-features to `cargo metadata` when using `cargo upgrade --to-lockfile`

- src/bin/upgrade/main.rs
- src/fetch.rs
On my PC I spot an error there's no `.cargo/registry/index/*/.git/` directory. Diving into problem shows me that it's bare repo so it doesn't have such directory. I added code will switch to bare repo in case of an error with `.git` directory.
> Support of bare repositories of crates' registry

- src/registry.rs
Fix `Command failed due to unhandled error: No such file or directory (os error 2)`, when config file without extension dose not exists.
If both files exist, will use the file without the extension, as same as cargo.
> Cargo also reads config files without the .toml extension, such as .cargo/config. Support for the .toml extension was added in version 1.39 and is the preferred form. If both files exist, Cargo will use the file without the extension.
[Configuration](https://doc.rust-lang.org/cargo/reference/config.html)
> Read config files with  extension that added in version 1.39.

- src/bin/add/main.rs
- src/bin/upgrade/main.rs
- src/dependency.rs
- src/fetch.rs
Makes fetching of the remote index quiet when `cargo add --quiet` is performed. Closes #461.
> quieted cargo add Update message when --quiet

- Cargo.lock
- Cargo.toml
- src/bin/add/args.rs
- src/bin/rm/main.rs
- src/bin/upgrade/main.rs
1. Add `wrap_help` feature to clap
2. Enable `AppSettings::ColoredHelp`
3. Reorganize `after_help` messages
Before:
After:
There is still a line display incorrectly. That may due to some bugs of structopt or old version clap. Clap 3.0.0-beta.2 (which embeds the functionality of structopt) can display it correctly:
> Beautify help messages

- Cargo.lock
- Cargo.toml
- src/errors.rs
- src/fetch.rs
- src/registry.rs
This was inspired by running into errors where `cargo add inquire` was
not adding the latest version.  We've seen similar problems during the
development of `crates-index`, so hoping what they've done fixes this.
Even if it doesn't solve this problem, hopefully by nature of using a
shared crate means it will get more use and more eyes to make it more
reliable in the long term.
Handling retrying the index is annoying.  I opened
https://github.com/frewsxcv/rust-crates-index/issues/62
Note: in the next version of crates-index
- Opening an index will implicitly create it, so we won't be able to
differentiate in our message whether we are initializing or updating.
See https://github.com/frewsxcv/rust-crates-index/issues/61
- We will be able to open an Index by URL, which will allow us to …
> refactor: Punt index logic to crates-index

- tests/cargo-add.rs
- tests/cargo-rm.rs
- tests/cargo-upgrade.rs
- tests/test_manifest.rs
- tests/utils.rs
This automatically picks `target/release/` or `target/debug/`, depending on how `cargo test` was executed.
This is helpful for packaging because currently all dependencies need to be built a second time when executing tests.
`CARGO_BIN_EXE_` was introduced in rustc 1.43.0.
> Fix `cargo test --release` if no debug build is present

- Cargo.toml
- README.md
- src/bin/set-version/args.rs
- src/bin/set-version/errors.rs
- src/bin/set-version/main.rs
- src/bin/set-version/version.rs
- src/errors.rs
- src/manifest.rs
- src/version.rs
- tests/cargo-set-version.rs
- tests/fixtures/set-version/Cargo.toml.sample
- tests/utils.rs
The name is not `version` because `cargo version` reports cargo's
version number.
The UI and implementation are lifted from `cargo-release`
Differences with `cargo-release`:
- Relative version changes is behind `--bump` rather than overloading
the positional argument
- Motivation: It didn't jive with `set-` in the name
- Side benefit: Better error reporting
Differences with #414:
- `--bump <level>` vs `--<level>`
- `--bump` scales better
- This PR supports `--metadata`, `--exclude`
Required future work
- Update workspace dependents when modifying versions
Possible future work
- `--at-least` flag to ignore downgrades, rather than error
- A flag to upgrade everything to the highest requested version (keep
things in lockstep with `--bump patch`)
- A flag to upgrade min requirements on …
> feat: MVP for `cargo set-version`

- Cargo.lock
- Cargo.toml
- tests/cargo-add.rs
- tests/cargo-rm.rs
- tests/cargo-upgrade.rs
- tests/test_manifest.rs
- tests/utils.rs
`assert_cli` has been deprecated for at least 3 years with `assert_cmd`
being the replacement.  This is also minimally introducing the
companion, `assert_fs` but doesn't retrofit code to fully take advantage
of it, yet.
> refactor(tests): Update assert_cli to assert_cmd

- src/bin/add/main.rs
- src/bin/rm/main.rs
- src/fetch.rs
- src/manifest.rs
For local content.  This is prep for fixing some bugs with workspaces
where `Dependency` has a path relative from the wrong location.  My plan
to fix it so for `Depednency` to have an absolute path.  Creating and
serializing `Dependency` will then require knowing what the path is for
the relevant manifest so we can handle converting the path.
> refactor: Exclusively switch to LocalManifest

- tests/cargo-add.rs
- tests/cargo-upgrade.rs
I'm getting test failures occasionally; I think github is rate limiting
me.  I added new tests, based on tests without `CARGO_IS_TEST`.  To
avoid others running into this in the future, I figured it'd be good to
apply it to all tests that don't touch the registry, whether they need
it or not.  This will also make the code more refactor-proof.
> test: Always skip registry updates

- src/bin/rm/main.rs
- tests/cargo-rm.rs
- tests/fixtures/rm/Cargo.toml.sample
(if no more crate references)
Fixes: #490
E.g. running the below on cargo-edit would then mean that cargo would complain that the git2 features ( `"git2/vendored-openssl"` ) couldn't be found:
```
cargo run --bin cargo-rm -- rm git2
```
After this PR, cargo would consider the Cargo.toml to be valid and rustc would legitimately complain that it could not find crate git2 (which makes perfect sense).
(An aside: The why: this change helps tools like udeps and undepend find and remove unused dependencies more successfully).
> rm should drop associated features

- Cargo.lock
- Cargo.toml
- src/bin/add/args.rs
- src/crate_name.rs
- src/dependency.rs
- src/lib.rs
- src/manifest.rs
- tests/cargo-add.rs
- tests/utils.rs
We originally treated `--path` as relative to each crate being added
instead of relative to the current working directory.  This caused users
confusion and doesn't work with tab completion.
Now, we'll treat the relative path as if its relative to the current
working directory, adapting it for each crate root.
I went back and forth on how to handle the tests.  Existing tests rely
on reusable fixtures, backed by files with functions to set them up.  I
considered updating the functions to produce fixtures needed for the new
local file requirements (paths exist) or to create new functions.  In
the end, I went with customizing it per function.  This made it so
assumptions in the test are contained within the test (e.g. dependency
name) rather than being split in separate areas.  It also made …
> fix(add): Form correct path dependencies

- src/bin/add/args.rs
- src/bin/add/main.rs
- tests/cargo-add.rs
If the user doesn't specify anything beyond a positional name or path,
we'll check if its a workspace member and add it according to workspace
best practices
- Use `version` and `path` for published dependencies so it uses the
local version for dev and the upcoming version on publish
- Use `path` for unpublished dependencies for development without
creating version bumping cycles.
Fixes #480
> feat(add): Workspace support

- src/bin/add/args.rs
- src/bin/add/main.rs
- src/bin/rm/main.rs
- src/bin/set-version/main.rs
- src/bin/upgrade/main.rs
- src/lib.rs
- src/metadata.rs
- tests/utils.rs
We called into `cargo_metadata` without setting the manifest path, so it used the CWD.
I verified that at least `--workspace` is relative to `--manifest-path` in `cargo build`.
> fix: Respect --manifest-path

- Cargo.lock
- Cargo.toml
- src/bin/add/args.rs
- src/crate_name.rs
- src/dependency.rs
- src/manifest.rs
- src/metadata.rs
In a PR I'm working on, I'm trying to take a canonicalized path and add
a relative path to it but that doesn't seem to be supported with UNC
paths, so I need dunce's "simplified" paths to then perform resolve
relative paths.
> refactor: Canonicalize via `dunce`

- src/bin/set-version/main.rs
- src/errors.rs
- src/lib.rs
- src/manifest.rs
- src/version.rs
- tests/cargo-set-version.rs
This will preserve both the comparator (like `^`) and number of version
field (`2.0` vs `2.0.0`) as we modify dependents in the workspace as we
modify versions.
> feat(version): Update dependents in workspace

- Cargo.toml
This is an issue for out-of-date system libgit2 packages.
See #510, #487.
> enable vendored-libgit2 by default

- src/bin/rm/main.rs
- tests/cargo-rm.rs
- tests/fixtures/rm/Cargo.toml.no_features.sample
- tests/fixtures/rm/Cargo.toml.sample
If a dependency was removed but there was no features in that Cargo.toml then an empty features table was added.
UPDATE: Failing test and fix done. (Sorry I didn't spot it earlier!)
> BUGFIX: Rm activated features accidently created empty features table

- README.md
> README: Add packaging status for cargo-edit

- Cargo.lock
- Cargo.toml
- src/fetch.rs
I use cargo's net.git-fetch-with-cli and the git `http.<host>.extraheader` config to interact with my company's authenticated crates-io mirror.
This doesn't work with cargo-edit 0.8.0 due to the switch to using rust-crates-index. With  https://github.com/frewsxcv/rust-crates-index/pull/69 I can get my setup working by using a git credential helper, so this PR just bumps rust-crates-index so I can use that.
> Update crates-index to 0.18.1

- src/dependency.rs
- src/fetch.rs
- src/manifest.rs
- src/registry.rs
Before, functions were scattered in the files.  Now. each mod starts
with a `pub` and groups impl blocks next to their related item, making
it easier to discover related logic.
> refactor: Raise visibility of pub items

- src/bin/add/args.rs
- src/crate_name.rs
- src/fetch.rs
- src/lib.rs
Both the loading from inferred url/path and the explicit can now reuse
logic from each other.
> refactor: Make manifest loading reusable

- src/bin/add/args.rs
- src/bin/add/main.rs
- src/crate_name.rs
- src/dependency.rs
- src/fetch.rs
- src/manifest.rs
- tests/cargo-add.rs
- tests/fixtures/add/Cargo.toml.features
This one is to address #529 and does precisely that. One decision I made that the reviewer might want to consider is that I didn't add this functionality when using `cargo-add` to add specific versioned crates. That was mostly because that currently doesn't have to hit either the file system or the registry and I didn't want to add that there and basically duplicate all the effort, nor did I want to try and refactor the whole thing in this PR so for now I just left it. If this is something people would like to see I'm willing to work on that. Otherwise it's a relatively small PR, mostly just connecting the dots on work that was already done, so hopefully it will be an easy merge. 
I also still have a draft PR (#528) that is related to this, and will at the least be easier to implement if …
> list available features when adding a dependency through cargo-add

- src/fetch.rs
This builds on #538 to add more coverage to #529.  We are now covering
the case where a user specifies only a name.  We are still missing
the case of specifying a name and version.
```
$ cargo-add serde
Finished dev [unoptimized + debuginfo] target(s) in 0.21s
Running `target/debug/cargo-add add serde`
Updating 'https://github.com/rust-lang/crates.io-index' index
Adding serde v1.0.130 to dependencies. 
Available features: 
- unstable
- default
- alloc
- rc
- std
- derive
```
> feat: Get features from registry

- src/bin/add/args.rs
- src/bin/upgrade/main.rs
- src/fetch.rs
- src/lib.rs
This should cover the last gap for closing out #529
```
cargo-add serde@1
Compiling cargo-edit v0.8.0 (/home/epage/src/personal/cargo-edit)
Finished dev [unoptimized + debuginfo] target(s) in 4.60s
Running `target/debug/cargo-add add 'serde@1'`
Updating 'https://github.com/rust-lang/crates.io-index' index
Adding serde v1 to dependencies.
Available features:
- derive
- default
- alloc
- std
- rc
- unstable
```
Fixes #529
> feat: Report features with `name@ver` deps

- src/bin/add/args.rs
- src/bin/add/main.rs
- src/bin/upgrade/main.rs
- src/dependency.rs
- src/fetch.rs
- src/manifest.rs
- tests/cargo-add.rs
Addresses #474. Was surprisingly easy after #538 was merged. Some of tests had to be slightly modified since they couldn't use non-existent features for testing anymore, but in spirit they remain the same. Perhaps one day we could even recommend options with fuzzy search but I think that one is for another day. 
Fixes #474
> cargo add now validates features against manifest before adding

- src/fetch.rs
This makes the warning printed by `cargo-add` upon renaming a dependency go to `stderr` instead of `stdout`. Closes #549.
> made dependency rename warning go to stderr

- Cargo.lock
- Cargo.toml
- src/bin/add/main.rs
- src/bin/rm/main.rs
- src/bin/set-version/main.rs
- src/bin/upgrade/main.rs
- src/fetch.rs
- src/lib.rs
- src/manifest.rs
- src/util.rs
- We were checking stdout for a TTY, rather than stderr
- We were sometimes forcing color, independent of TTY, `TERM`, or
`NO_COLOR`
- We were using `atty` without requiring it
This switches us to `concolor-control`, a crate from WG-CLI meant to
encapsulate color choice policy.  Unlike termcolor, it also handles TTY
detection and `CLICOLOR` spec, and true-color detection.   Its setup
where someone depending on `cargo-edit` will get no color support.  They
can then opt-in to color support.  A `color` feature is offered to allow users to opt-in to colored output without depending on `concolor-control`.
The low version number is mostly as we wait for feedback from
`termcolor` at which point we'll get it 1.0 and make the entire API
stable (there is an `unstable-` feature flag).
Fixes #557
> fix: Handle colors correctly

- src/crate_name.rs
There isn't a definitive way for us to know this is a git url from
another url from anything else which can limit future evolution.
We still have `--git` support.
> fix(add)!: Remove implicit git support

- src/bin/add/args.rs
- src/bin/add/main.rs
- tests/cmd/add/git.toml
- tests/cmd/add/git_branch.toml
- tests/cmd/add/git_conflicts_namever.toml
- tests/cmd/add/git_conflicts_registry.toml
- tests/cmd/add/git_dev.toml
- tests/cmd/add/git_rev.toml
- tests/cmd/add/git_tag.toml
- tests/cmd/add/invalid_git_no_unstable.in
- tests/cmd/add/invalid_git_no_unstable.out/Cargo.toml
- tests/cmd/add/invalid_git_no_unstable.toml
- tests/cmd/add/multiple_conflicts_with_git.toml
- tests/cmd/add/overwrite_version_with_git.toml
There are aspects we still need to figure out
- Separate `--branch`... flags,
or `#branch=<branch>`... fragments
or `#<branch|tag|rev>` fragment
- Can we integrate it into the crate-spec to fit in with the multi-add
workflow?  (see #578 for issues)
- Should we allove overwriting these by crate name without re-specifying
git url?
> fix(add): Feature-gate `--git`

- Cargo.lock
- Cargo.toml
- src/dependency.rs
- src/manifest.rs
We are wanting "modify" to
- Append features
- Handle optional well (#298) and default-features
- Not change version
To do this, we need to merge at a higher level.  This makes it so we now merge with the `Dependency` data structure rather than doing toml to toml merge.
> refactor: Prepare for new `modify` logic

- Cargo.lock
- Cargo.toml
- src/dependency.rs
- tests/cmd/add/overwrite_features.out/Cargo.toml
Take
```console
$ cargo add clap --features derive
$ cargo add clap --features unicode
```
Before, this would result in
```toml
clap = { version = "3.0.13", features = ["unicode"] }
```
Now, it results in
```toml
clap = { version = "3.0.13", features = ["derive", "unicode"] }
```
This is part of a larger effort to make `cargo add` "append-only".  We
should only modify fields users explicitly mention and, when we do, we
should append-or-replace (depending on the data type).
> fix(add)!: Re-adding appends features

- README.md
- src/bin/add/args.rs
- src/bin/upgrade/main.rs
- src/crate_spec.rs
- tests/cmd/add/default_features.toml
- tests/cmd/add/git_conflicts_namever.toml
- tests/cmd/add/invalid_vers.toml
- tests/cmd/add/namever.toml
- tests/cmd/add/no_default_features.toml
- tests/cmd/add/no_optional.toml
- tests/cmd/add/optional.toml
- tests/cmd/add/overwrite_default_features.toml
- tests/cmd/add/overwrite_default_features_with_no_default_features.toml
- tests/cmd/add/overwrite_no_default_features.toml
- tests/cmd/add/overwrite_no_default_features_with_default_features.toml
- tests/cmd/add/overwrite_no_optional.toml
- tests/cmd/add/overwrite_no_optional_with_optional.toml
- tests/cmd/add/overwrite_optional.toml
- tests/cmd/add/overwrite_optional_with_no_optional.toml
- tests/cmd/add/vers.toml
- tests/cmd/upgrade/to_version.toml
This reverts commit 36c9a1b97242c2fd634d4e47e91d8201d5e816cd.
There is interest in changing cargo, instead of changing `cargo add`.
> Revert "fix(add)!: Use `:` from pkgid, rather than `@`"

- src/bin/add/main.rs
I had assumed we were using clap for the splitting and was holding off
until we could use cargo's infrastructure for this.
Turns out we did it ourselves and its easy to add comma support.
> fix(add): Allow ',' to separate features

- src/bin/add/args.rs
- src/bin/add/main.rs
We need a fully populated `dependency` to check the old version in one specific case.
> refactor(add): Prepare to not overwrite version

- src/fetch.rs
Our two paths for looking at the registry for tests didn't align.  Now
they do.  This will help future changes.
> test: Ensure we always populate test data

- README.md
- src/bin/add/args.rs
This is serving as a "living" proposal for `-F` to be added to cargo
generally.  Before, we've rejected this because we wanted to mirror
cargo.
`-F` was chosen because `-f`'s de facto meaning is `--force`.  Even if
we don't have a `--force` flag, a cargo command could in the future and
we don't want conflicts.
Fixes #450
> feat(add): Add `-F` short flag

- src/bin/add/args.rs
- src/manifest.rs
- tests/cmd/add/prefer_existing_version.in/.cargo/config
- tests/cmd/add/prefer_existing_version.in/Cargo.toml
- tests/cmd/add/prefer_existing_version.in/dependency/Cargo.toml
- tests/cmd/add/prefer_existing_version.out/Cargo.toml
- tests/cmd/add/prefer_existing_version.out/dependency/Cargo.toml
- tests/cmd/add/prefer_existing_version.toml
When adding a dependency to multiple tables, most likely the user
intends to use the same version across all of them.  We should prefer
the existing version requirement, registry, and path.
This was inspired by an [internals post](https://internals.rust-lang.org/t/allow-omission-of-version-for-dev-and-build-dependencies-that-are-also-regular-dependencies/16077) where a user wanted to elide the version in dev/build dependencies when it also exists in the regular
dependencies
> fix(add): Prefer copying existing dep requirements 

- src/manifest.rs
Currently, `update_table_named_entry` calls `self.path.parent()` twice to determine the `crate_root`.
Moreover, `update_table_named_entry` creates `new_dependency` outside of the `if` block, even though `new_dependency` is needed only inside of the `if` block.
This small change resolves these two inefficiencies.
(These observations are a consequence of #613. But this change is not needed to implement #613.)
> Improve `update_table_named_entry`

- src/bin/upgrade/main.rs
- src/dependency.rs
- src/manifest.rs
For #613, we need an unprocessed version requirement.  This requires us from using data from `LocalManifest` instead of  `cargo_metadata` .
> refactor(upgrade): Track raw manfiest data

- Cargo.lock
- Cargo.toml
- src/fetch.rs
This pull request updates the `ureq` dependency to version 2.4.
By upgrading this dependency, TLS libraries like `ring`, `rustls` and `webpki` are also updated with `ureq`.
> feat(fetch): upgrade ureq to 2.4

- Cargo.lock
- Cargo.toml
- src/fetch.rs
This pull request adds support for more CPU architectures (including several Rust Tier-2h targets).
The main issue is that `ureq` by default uses `ring` which only supports a total of 2 architecture families: `x86` and `arm` (and `ring` upstream did not plan to support other architectures any time soon).
This pull request resolves this issue by using `native-tls` instead of `ring` + `rustls` on "other architectures".
Due to limitations with the current `cargo` manifest format, the manifest change is a bit hacky. See https://github.com/rust-lang/cargo/issues/1197 for details on this limitation.
------
Blocked by #622 (needs to update `ureq` to 2.x in order to gain the ability to change TLS backend)
> feat(fetch): add support for more CPU architectures

- Cargo.toml
- src/bin/add/add.rs
- src/dependency.rs
- src/fetch.rs
- src/manifest.rs
- tests/cmd/add/add_normalized_name_external.toml
- tests/cmd/add/features.toml
- tests/cmd/add/features_empty.toml
- tests/cmd/add/features_multiple_occurrences.toml
- tests/cmd/add/features_preserve.toml
- tests/cmd/add/features_spaced_values.toml
- tests/cmd/add/features_unknown.toml
- tests/cmd/add/git_external.toml
- tests/cmd/add/list_features.toml
- tests/cmd/add/list_features_path.toml
- tests/cmd/add/overwrite_features.toml
- tests/cmd/add/overwrite_inline_features.toml
Before, we showed a list of activated features (comma-separated) and all features (bulleted).
Now, we'll show a bulleted list of all features with a `+` or `-` (colored) signifying whether they are activated.  This includes default-activated features.
Additionally, `default` no longer (sometimes) shows up in the list.
> fix(add): Don't show two separate feature lists

- crates/cargo-add/src/bin/cargo/commands/add.rs
- crates/cargo-add/src/cargo/ops/cargo_add/crate_spec.rs
- crates/cargo-add/src/cargo/ops/cargo_add/dependency.rs
- crates/cargo-add/src/cargo/ops/cargo_add/manifest.rs
- crates/cargo-add/src/cargo/ops/cargo_add/mod.rs
- crates/cargo-add/tests/snapshots/add/add_normalized_name_external.stderr
- crates/cargo-add/tests/snapshots/add/deprecated_default_features.in/Cargo.toml
- crates/cargo-add/tests/snapshots/add/deprecated_default_features.out/Cargo.toml
- crates/cargo-add/tests/snapshots/add/deprecated_default_features.stderr
- crates/cargo-add/tests/snapshots/add/deprecated_section.in/Cargo.toml
- crates/cargo-add/tests/snapshots/add/deprecated_section.out/Cargo.toml
- crates/cargo-add/tests/snapshots/add/deprecated_section.stderr
- crates/cargo-add/tests/snapshots/add/features_unknown.stderr
- crates/cargo-add/tests/snapshots/add/git_conflicts_namever.stderr
- crates/cargo-add/tests/snapshots/add/infer_prerelease.in
- crates/cargo-add/tests/snapshots/add/infer_prerelease.out/Cargo.toml
- crates/cargo-add/tests/snapshots/add/infer_prerelease.stderr
- crates/cargo-add/tests/snapshots/add/invalid_inline_path_self.stderr
- crates/cargo-add/tests/snapshots/add/invalid_name_external.stderr
- crates/cargo-add/tests/snapshots/add/invalid_vers.stderr
- crates/cargo-add/tests/snapshots/add/multiple_conflicts_with_features.stderr
- crates/cargo-add/tests/snapshots/add/multiple_conflicts_with_git.stderr
- crates/cargo-add/tests/snapshots/add/multiple_conflicts_with_rename.stderr
- crates/cargo-add/tests/snapshots/add/overwrite_name_dev_noop.stderr
- crates/cargo-add/tests/snapshots/add/overwrite_name_noop.stderr
- crates/cargo-add/tests/snapshots/add/overwrite_path_noop.stderr
- crates/cargo-add/tests/testsuite/cargo_add.rs
> Apply feedback on merge into cargo

- src/fetch.rs
This pull request simply fixes a regression introduced in b5d052e4e51c7cbf8506a284615551fabc2f0cd9 where the return type of the function changed but the error type returned wasn't.
> fix(fetch): fix a regression introduced in `b5d052e4e51c7cbf8506a284615551fabc2f0cd9`

- tests/cmd/upgrade/invalid_workspace_root_manifest.toml
Cargo 1.60.0-stable has been released, the test `invalid_workspace_root_manifest` begins to fail as you said in https://github.com/killercup/cargo-edit/pull/655#issuecomment-1054311061.
```
Testing tests/cmd/upgrade/invalid_workspace_root_manifest.toml ... failed
Exit: 1
stdout:
---- expected: stderr
++++ actual:   stderr
1    1 | Error: Failed to get workspace metadata
2    2 | 
3    3 | Caused by:
4    4 |     `cargo metadata` exited with an error: error: failed to parse manifest at `[CWD]/Cargo.toml`
5    5 |     
6    6 |     Caused by:
7    7 |       could not parse input as TOML
8    8 |     
9    9 |     Caused by:
10      -       expected an equals, found an identifier at line 1 column 6
10 +       TOML parse error at line 1, column 6
11 +         |
12 +       1 | This is clearly …
```
> Partially match `stderr` for 'invalid_workspace_root_manifest'

- src/bin/set-version/set_version.rs
- src/metadata.rs
- tests/cmd/set-version/upgrade_workspace.in
- tests/cmd/set-version/upgrade_workspace.out/Cargo.toml
- tests/cmd/set-version/upgrade_workspace.out/dependency/Cargo.toml
- tests/cmd/set-version/upgrade_workspace.out/primary/Cargo.toml
- tests/cmd/set-version/upgrade_workspace.toml
We load all manifests up front and and then iteratively update and write
them out.  The problem is between load and update/write, we might have
processed another manifest and updated the dependency table in the other
manifest, causing the last writer to win and updates to be lost.
Our tests haven't forced this situation yet.  We inherited this from
`upgrade` but since it only write to one at a time, it doesn't have the
last-writer-wins problem.
Fixes #702
> fix(set-version): Don't overwrite dependency updates 

- Cargo.lock
- Cargo.toml
I edited the Cargo.toml to update toml_edit version and I run `cargo update -p trycmd` so that users don't have to compile to versions of toml_edit
> chore: update toml_edit to v0.14

- src/bin/rm/rm.rs
- src/bin/upgrade/upgrade.rs
- src/fetch.rs
- src/lib.rs
- src/manifest.rs
- src/util.rs
- tests/cmd/upgrade/alt_registry.toml
- tests/cmd/upgrade/dry_run.toml
- tests/cmd/upgrade/dry_run_prerelease.toml
- tests/cmd/upgrade/exclude_dep.toml
- tests/cmd/upgrade/exclude_renamed.toml
- tests/cmd/upgrade/implicit_prerelease.toml
- tests/cmd/upgrade/optional_dep.toml
- tests/cmd/upgrade/prerelease.toml
- tests/cmd/upgrade/preserve_precision_major.toml
- tests/cmd/upgrade/preserve_precision_minor.toml
- tests/cmd/upgrade/preserve_precision_patch.toml
- tests/cmd/upgrade/single_dep.toml
- tests/cmd/upgrade/skip_compatible.toml
- tests/cmd/upgrade/skip_pinned.toml
- tests/cmd/upgrade/specified.toml
- tests/cmd/upgrade/to_lockfile.toml
- tests/cmd/upgrade/to_version.toml
- tests/cmd/upgrade/upgrade_all.toml
- tests/cmd/upgrade/upgrade_everything.toml
- tests/cmd/upgrade/upgrade_renamed.toml
- tests/cmd/upgrade/upgrade_workspace.toml
- tests/cmd/upgrade/workspace_member_cwd.toml
Use utility functions to simplify styling and make the existing styling and indentation more consistent.
A few instances of manual styling remain:
- In the deprecation messages in `set_version.rs` and `upgrade.rs` (these could use an aesthetic pass too though, since they look out of place).
- In the feature activation list of `set_version`.
- In cargo add, per review discussion.
This also serves as a step towards #682, as these utilities functions are similar in form to Cargo's shell output.
> Clean up custom console output with utils

- src/bin/upgrade/upgrade.rs
- src/errors.rs
- src/manifest.rs
The interaction with `--skip-compatible` is not ideal, so holding off on actually stablizing for now.
> fix(upgrade): Prepare for stablizing preserve-precsion

- src/bin/upgrade/upgrade.rs
With path and git dependencies, you can specify a version for use with
the registry.  If its incompatible, I believe the resolver will fail, so
we don't need to handle that case.  That just leaves `--to-lockfile`.
This just means post-poning the check for the registry to be in the
non-lockfile case.
Fixes #426
> fix(upgrade): `--to-lockfile` changes all sources

- src/bin/upgrade/upgrade.rs
- src/lib.rs
- src/util.rs
- tests/cmd/upgrade/pinned.toml
- tests/cmd/upgrade/skip_compatible.toml
I was surprised to see nothing happen and I realized users could use a
hint that `--to-lockfile` is a thing to upgrade all version reqs.
> fix(upgrade): Provide hint when nothing happens

- src/bin/upgrade/upgrade.rs
- tests/cmd/upgrade/exclude_renamed.toml
- tests/cmd/upgrade/pinned.toml
Like with compatible requirements, this provides a way to let people
know that some version reqs were unchanged in a succinct way.
> fix(upgrade): Report when pinned are present

- README.md
- src/bin/rm/rm.rs
- Use derive display ordering.
- Tweak help messages to be in line with Cargo.
- Remove periods from doc strings (not sure I love this, but it does make it in line with cargo add).
- Use consistent grammatical case.
Furthers #682.
> Clean up rm arguments

- Cargo.lock
- Cargo.toml
Matches similar bump in Cargo ([ed78e6b](https://github.com/rust-lang/cargo/commit/ed78e6b7471a2e7b101354c1570bbb32e9aee9f9)).
> Bump snapbox to 0.3

- README.md
- crates/cargo-rm/Cargo.toml
- crates/cargo-rm/src/bin/cargo/cli.rs
- crates/cargo-rm/src/bin/cargo/commands/mod.rs
- crates/cargo-rm/src/bin/cargo/commands/rm.rs
- crates/cargo-rm/src/bin/cargo/main.rs
- crates/cargo-rm/tests/testsuite/cargo_rm/invalid_arg/mod.rs
- crates/cargo-rm/tests/testsuite/cargo_rm/invalid_dep/mod.rs
- crates/cargo-rm/tests/testsuite/cargo_rm/invalid_dep/stderr.log
- crates/cargo-rm/tests/testsuite/cargo_rm/invalid_rm_target/mod.rs
- crates/cargo-rm/tests/testsuite/cargo_rm/invalid_rm_target/stderr.log
- crates/cargo-rm/tests/testsuite/cargo_rm/invalid_rm_target_dep/mod.rs
- crates/cargo-rm/tests/testsuite/cargo_rm/invalid_rm_target_dep/stderr.log
- crates/cargo-rm/tests/testsuite/cargo_rm/invalid_section/mod.rs
- crates/cargo-rm/tests/testsuite/cargo_rm/invalid_section/stderr.log
- crates/cargo-rm/tests/testsuite/cargo_rm/invalid_section_dep/mod.rs
- crates/cargo-rm/tests/testsuite/cargo_rm/invalid_section_dep/stderr.log
- crates/cargo-rm/tests/testsuite/cargo_rm/no_arg/mod.rs
This PR converts rm's arg parsing to clap builder with minimal changes to functionality. After this is merged, I will start working on using more cargo internals in the argument parsing, which will have more noticeable effects.
> Use clap builder instead of derive, restructure a bit to look like cargo

- crates/cargo-remove/src/bin/cargo/commands/remove.rs
- crates/cargo-remove/src/cargo/ops/cargo_remove/dependency.rs
- crates/cargo-remove/src/cargo/ops/cargo_remove/manifest.rs
- crates/cargo-remove/src/cargo/ops/cargo_remove/mod.rs
This PR adds the changes made to `{dependency,manifest,metadata}.rs` in cargo's cargo add. This is done in two parts: with ec94271 directly copying over the changes and breaking cargo remove with the removal of `remove_from_table` in the process, and with 8fbd033 re-adding that missing function. This is done primarily for the ease of review, so it might be best to squash these two commits.
> Use utils from cargo add

- README.md
- src/bin/upgrade/upgrade.rs
- tests/cargo-upgrade/invalid_dep/mod.rs
- tests/cargo-upgrade/invalid_flag/stderr.log
- tests/cargo-upgrade/invalid_manifest/stderr.log
- tests/cargo-upgrade/invalid_workspace_root_manifest/mod.rs
- tests/cargo-upgrade/invalid_workspace_root_manifest/stderr.log
- tests/cargo-upgrade/preserve_precision_major/mod.rs
- tests/cargo-upgrade/preserve_precision_minor/mod.rs
- tests/cargo-upgrade/preserve_precision_patch/mod.rs
- tests/cargo-upgrade/specified/mod.rs
- tests/cargo-upgrade/to_lockfile/mod.rs
- tests/cargo-upgrade/to_lockfile/stderr.log
- tests/cargo-upgrade/to_version/mod.rs
- tests/cargo-upgrade/upgrade_all/mod.rs
- tests/cargo-upgrade/upgrade_all/stderr.log
- tests/cargo-upgrade/upgrade_workspace/mod.rs
- tests/cargo-upgrade/upgrade_workspace/stderr.log
- tests/cargo-upgrade/virtual_manifest/stderr.log
- tests/cargo-upgrade/workspace_member_cwd/mod.rs
- tests/cargo-upgrade/workspace_member_cwd/out/Cargo.lock
- tests/cargo-upgrade/workspace_member_cwd/out/explicit/four/Cargo.toml
- tests/cargo-upgrade/workspace_member_cwd/out/implicit/three/Cargo.toml
- tests/cargo-upgrade/workspace_member_cwd/out/two/Cargo.toml
- tests/cargo-upgrade/workspace_member_cwd/stderr.log
- tests/cargo-upgrade/workspace_member_manifest_path/mod.rs
- tests/cargo-upgrade/workspace_member_manifest_path/out/explicit/four/Cargo.toml
- tests/cargo-upgrade/workspace_member_manifest_path/out/implicit/three/Cargo.toml
- tests/cargo-upgrade/workspace_member_manifest_path/out/two/Cargo.toml
- tests/cargo-upgrade/workspace_member_manifest_path/stderr.log
This came from the internals discussion on what `cargo upgrade` should look like in cargo.
See https://internals.rust-lang.org/t/feedback-on-cargo-upgrade-to-prepare-it-for-merging/17101
Benefits
- Removes the UI conflict in selecting manifests to edit and selecting dependencies to upgrade
- Will work naturally with `[workspace.dependencies]`
- If we merge `upgrade` into `update` or supersede it, we'll already be aligned on behavior
> fix(upgrade)!: Exclusively operate on full workspaces

- README.md
- src/bin/upgrade/upgrade.rs
In the spirit of seeing how `cargo upgrade` could replace `cargo
update`, this is another take on the `--aggresive` flag, controlling how
we handle indirect dependencies in the lock file.
> feat(upgrade): Add --recursive=<bool> flag 

- src/bin/upgrade/upgrade.rs
- tests/cargo-upgrade/dry_run/stderr.log
Ideally we'd still report messages but keeping things simple for now.
> fix(upgrade): Don't touch lockfile in dry-run

- CHANGELOG.md
- README.md
- src/bin/upgrade/upgrade.rs
Changed `--compatible`, `--incompatible`, and `--pinned` from accepting `true|false` to `allow|ignore` (with aliases for compatibility
While we are still working out how we want to express these options, this at least removes the confusion over `--compatible false` looking like it is the same as `--incompatible`.
> fix(upgrade): Change the values for --compatible and friends

- src/bin/upgrade/upgrade.rs
- src/errors.rs
- src/manifest.rs
There were two problems
- We can't use `--aggresive` with `--precise`
- We soemtimes need to download new index entries but that failed, causing us our tests to not hit the above bug
Fixes #823
> fix(upgrade): Ensure precise updates handled

- src/bin/upgrade/upgrade.rs
This is inspired by talks in how to handle MSRV, see rust-lang/cargo#9930.
For now, I coalesce for "longer" lists but maybe we should do it always?
> fix(upgrade): Coalesce long summaries

- README.md
- src/bin/upgrade/upgrade.rs
- tests/cargo-upgrade/exclude_dep/mod.rs
- tests/cargo-upgrade/exclude_renamed/mod.rs
- tests/cargo-upgrade/lockfile/mod.rs
- tests/cargo-upgrade/pinned/mod.rs
- tests/cargo-upgrade/preserve_op/mod.rs
- tests/cargo-upgrade/preserve_precision_major/mod.rs
- tests/cargo-upgrade/preserve_precision_minor/mod.rs
- tests/cargo-upgrade/preserve_precision_patch/mod.rs
- tests/cargo-upgrade/skip_compatible/mod.rs
- tests/cargo-upgrade/specified/stderr.log
- tests/cargo-upgrade/specified/stdout.log
- tests/cargo-upgrade/to_version/mod.rs
- tests/cargo-upgrade/upgrade_all/mod.rs
- tests/cargo-upgrade/upgrade_everything/stderr.log
- tests/cargo-upgrade/upgrade_renamed/mod.rs
- tests/cargo-upgrade/upgrade_verbose/mod.rs
- tests/cargo-upgrade/upgrade_workspace/mod.rs
- tests/cargo-upgrade/virtual_manifest/mod.rs
- tests/cargo-upgrade/workspace_inheritance/stderr.log
- tests/cargo-upgrade/workspace_member_cwd/stderr.log
- tests/cargo-upgrade/workspace_member_manifest_path/stderr.log
`--verbose` is required for these.  The old `--verbose` is now
`--verbose --verbose` (extra verbose).
> fix(upgrade): Hide upgradeable by default 

- README.md
- src/bin/upgrade/upgrade.rs
- tests/cargo-upgrade/to_version/stderr.log
Recursive dependency updating is compatible dependency updating and we should respect it if users disable compatible upgrades.
See also killercup/cargo-edit#812
> fix(upgrade)!: Default --recursive to --compatible

- README.md
- src/bin/upgrade/upgrade.rs
- src/fetch.rs
- src/lib.rs
- tests/cargo-upgrade/cli_rust_version/in/Cargo.toml
- tests/cargo-upgrade/cli_rust_version/mod.rs
- tests/cargo-upgrade/cli_rust_version/out/Cargo.toml
- tests/cargo-upgrade/cli_rust_version/stderr.log
- tests/cargo-upgrade/cli_rust_version/stdout.log
- tests/cargo-upgrade/ignore_rust_version/in/Cargo.toml
- tests/cargo-upgrade/ignore_rust_version/mod.rs
- tests/cargo-upgrade/ignore_rust_version/out/Cargo.toml
- tests/cargo-upgrade/ignore_rust_version/stderr.log
- tests/cargo-upgrade/ignore_rust_version/stdout.log
- tests/cargo-upgrade/main.rs
- tests/cargo-upgrade/package_rust_version/in/Cargo.toml
- tests/cargo-upgrade/package_rust_version/mod.rs
- tests/cargo-upgrade/package_rust_version/out/Cargo.toml
- tests/cargo-upgrade/package_rust_version/stderr.log
- tests/cargo-upgrade/package_rust_version/stdout.log
We'll limit compatible and incompatible ugprades to ones that are MSRV compatible which can be overridden with either `--ignore-rust-version` or `--rust-version <VER>`.
Unlike rust-lang/cargo#12078, there aren't great warnings and error messages.  This is because the current structure makes it a little uglier but the hope is future plans for the UI will make it easier to do these, so we'll defer until then
> feat(upgrade): Respect package.rust-version

- Cargo.lock
- Cargo.toml
The proc-macro2 package is old and it is not possible to compile it with a recent nightly compiler
> fix: Allow building on recent nightlies

- Cargo.lock
- Cargo.toml
looks like removing this from the top level Cargo.toml was missed during https://github.com/killercup/cargo-edit/pull/662
> remove unused ureq dep

- README.md
Remove the note about using the `vendored-openssl` feature to bundle openssl. This feature was removed in #907.
Fixes #908
> Remove vendored-openssl installation note from README

- README.md
Travis CI and AppVeyor were removed a long time ago, but their badges were forgotten.
> Removed Travis and AppVeyor badges

- src/errors.rs
- src/registry.rs
> fix(upgrade): Improve config error messages
