.travis.yml

Add travis-cargo

---

.gitignore
Cargo.lock
Cargo.toml
src/bin/list.rs
src/lib.rs
src/list.rs
src/list_error.rs
src/main.rs
src/manifest.rs
src/tree.rs
tests/cargo-list.rs
tests/fixtures/list/Cargo.toml

`cargo list <section> [--tree] [--help] [--manifest-path]`

cargo-list

---

.travis.yml
README.md
tests/shell_hook.rs

Travis says it doesn't respond for 10 minutes.

Skip Shell Tests in Coverage

---

Cargo.toml
LICENSE
README.md

New Readme for Separate Binaries

---

src/manifest.rs

by adding table/Dependency names as described in #25.

Nice Manifest Errors

---

Makefile
src/bin/rm/args.rs
src/bin/rm/main.rs
src/lib.rs
src/manifest.rs

Even Better NonExistentDependency Errors

---

src/bin/add/args.rs
tests/cargo-add.rs

Handle Optional Dependencies

---

src/bin/add/args.rs
src/bin/add/main.rs
tests/cargo-add.rs

There Can't Be Optional Dev Deps

---

src/bin/add/main.rs
src/bin/list/main.rs
src/bin/rm/main.rs
src/lib.rs

Also make each crate header look the same.

Make Lints Stricter

---

Cargo.lock
Makefile
src/bin/add/main.rs
src/bin/list/main.rs
src/bin/rm/main.rs
src/lib.rs
tests/cargo-add.rs
tests/cargo-rm.rs

- Fix `make fmt`
- Fix Clippy
- Update dependencies

Some maintainance work

---

src/bin/add/main.rs

Mention Cargo's Caret-As-Default Behavior

---

src/bin/add/args.rs
src/bin/add/main.rs
src/manifest.rs
tests/cargo-add.rs

Add --target <target> option to add dependencies to specific target platform (#13)

---

Cargo.toml
src/bin/add/args.rs
src/bin/add/fetch.rs
src/bin/add/main.rs
src/bin/list/list.rs
src/bin/list/main.rs
src/bin/list/tree.rs
src/bin/rm/args.rs
src/bin/rm/main.rs
src/manifest.rs
tests/cargo-add.rs
tests/utils.rs

I am working on a second try at #61 and wanted to submit a work in progress checkpoint to see if you're on board with the method for implementing the feature. I initially wanted to have docopt parse to a rust enum but couldn't quite figure that out so I figured that we could just handle invalid parameters sent to this flag with a panic. 
The code is different enough that I figured I would just start over from latest master. What do you think so far?

Upgrade flag another try at #61

---

src/bin/add/args.rs

Seems to solve the issue #92 and passes all tests.

Fix bug to allow adding multiple crates at once

---

Cargo.lock
Cargo.toml
src/bin/add/fetch.rs

Update to curl 0.4

---

.travis.yml

Set up bors-ng branches with Travis

---

.travis.yml
Cargo.lock
Cargo.toml
src/lib.rs
src/manifest.rs
tests/test_manifest.rs

Enable clippy

---

README.md
src/bin/rm/main.rs

and also minor correction to wording of `cargo rm` usage

Update README.md to match actual usage statements

---

Cargo.lock
Cargo.toml
src/fetch.rs
tests/cargo-add.rs
tests/cargo-rm.rs
tests/cargo-upgrade.rs
tests/test_manifest.rs

Upgrade `reqwest` and `assert_cli`, and run `cargo update`.

Upgrade dependencies

---

Cargo.toml

Also adds authors and mentions `cargo upgrade` in description.

Bump version to 0.2

---

tests/cargo-add.rs

fix for #154

---

README.md
src/bin/upgrade/main.rs
src/fetch.rs
tests/cargo-add.rs
tests/cargo-upgrade.rs

Hope I didn't miss anything. :)

Add `--allow-prerelease` flag to cargo upgrade. Closes #162

---

Cargo.lock
Cargo.toml
src/fetch.rs
src/lib.rs

Fixes #134.
cc @mkpankov, can you test this please?

add env proxy support

---

Cargo.lock
Cargo.toml
src/bin/upgrade/main.rs
src/dependency.rs
src/fetch.rs
src/lib.rs
src/manifest.rs
tests/cargo-add.rs
tests/cargo-rm.rs
tests/cargo-upgrade.rs
tests/fixtures/upgrade/Cargo.toml.source
tests/fixtures/upgrade/Cargo.toml.target
tests/test_manifest.rs
tests/utils.rs

cc #15, #69.
This is an experiment with [toml_edit](https://github.com/ordian/toml_edit) to figure out what the right API (https://github.com/LeopoldArkham/Molten/issues/8, cc @LeopoldArkham) is for the upcoming integration with Molten, but also can be useful by itself while Molten is not yet ready.
Basically, all we need is an `Item`, which can represent anything (`None`, `Table`, `InlineTable`, `String`, ...), `IndexMut<&str, Output=Item>` implementation for Item and a bunch of downcasting methods (`is_table`, `as_table`, ...).
Deleting an item is just replacing it with `None`.

Start world domination

---

.travis.yml
src/manifest.rs

Upgrade to Rustfmt 0.3.2 and clippy 0.0.176
Fixes #187

Get Rustfmt from rustup

---

README.md
src/bin/upgrade/main.rs
src/manifest.rs
tests/cargo-upgrade.rs

Run `cargo upgrade` without saving changes.
fixes #192

Add `--dry-run` flag

---

src/errors.rs

fix prerelease error description

---

src/bin/upgrade/main.rs

Fixes #203.
Not sure if this is a proper fix, but it seems to work.
r? @bjgill

Pass `--no-deps` flag to cargo metadata

---

README.md
src/bin/add/args.rs
src/bin/add/main.rs
src/dependency.rs
tests/cargo-add.rs

Allow simultaneous specification of both version and path

---

.travis.yml
Cargo.lock

Contains #225 and #229 and closes all other dependabot PRs
Closes #220
Closes #221 
Closes #222 
Closes #223 
Closes #224 
Closes #226
Closes #227
Closes #228

Upgrade deps

---

Cargo.toml

This is a trivial and style only change but as it is part of code, it
is also important.
Signed-off-by: Otavio Salvador <otavio@ossystems.com.br>

Cargo.toml: Add an empty line for badges definition

---

Cargo.lock
Cargo.toml
tests/test_manifest.rs

Release 0.3.1

---

.travis.yml
Cargo.lock
src/fetch.rs
src/manifest.rs

closes #266 
closes #275 
closes #276 
closes #286 
closes #287 
closes #288

CI maintenance

---

src/dependency.rs
tests/cargo-add.rs

Automatically strip semver metadata on versions

---

src/bin/add/args.rs
src/bin/add/main.rs
tests/cargo-add.rs
tests/fixtures/add/Cargo.toml.unsorted

Partial fix for #280
Is this pointing into the right direction?

Include sort flag for adding deps

---

src/bin/upgrade/main.rs
src/dependency.rs
src/manifest.rs
tests/cargo-upgrade.rs
tests/fixtures/upgrade/Cargo.toml.renamed_dep
tests/fixtures/upgrade/Cargo.toml.source
tests/fixtures/upgrade/Cargo.toml.target

Handle renamed dependencies

---

README.md

README: add a note about installation requisites

---

README.md
src/bin/add/args.rs
src/bin/add/main.rs
src/manifest.rs
tests/cargo-add.rs

feat: cargo-add renamed dependency

---

src/bin/upgrade/main.rs
tests/cargo-upgrade.rs

upgrade: do not downgrade prerelease dependencies

---

Cargo.lock
Cargo.toml
tests/cargo-upgrade.rs

make cli deps optional

---

Cargo.lock
Cargo.toml

bump version to 0.5.0

---

src/bin/upgrade/main.rs
tests/cargo-upgrade.rs

Add `--workspace` to cargo-upgrade and deprecate `--all`

---

Cargo.lock
Cargo.toml
README.md
appveyor.yml
src/bin/upgrade/main.rs
src/fetch.rs

notable changes:
* #379
* #390
* #392

release 0.6.0

---

src/dependency.rs
tests/cargo-add.rs

Normalise windows-style paths

---

src/fetch.rs
tests/cargo-add.rs

Fix fetch for non lowercase crate names

---

Cargo.lock
Cargo.toml

@sigmaSd, this bumps libgit2-sys to version 0.12.14+1.1.0. Can you confirm that this
fixes #429
Thanks!

Update a bunch of dependencies

---

Cargo.lock
Cargo.toml
src/errors.rs
src/fetch.rs

Quite a small change in LOC but a big one in number of dependencies. Compile times are not much improved for me, but around 35s for release mode wasn't really painful anyway.

Use ureq instead of reqwest

---

README.md

#434 
- Added compiler support to readme

Addresses #434 - Compiler Support 

---

Cargo.lock
Cargo.toml
src/registry.rs

Replace dirs dependency with dirs-next

---

.travis.yml
README.md
src/bin/upgrade/main.rs
tests/cargo-upgrade.rs

Hi,
First time contributor here in need of some mentorship for this one.
This is a PR for #318 adding an exclude option.
The basics work, but I'm not familiar enough with the project to say for sure if everything is good to go or not, and would appreciate some help too test if there are any issues.

Add exclude option

---

src/manifest.rs

Print "Upgrading" status for renamed dependencies

---

.github/workflows/build.yml

It uses a custom action that only cache's needed things.

Cache the CI better

---

src/bin/add/args.rs

I've not verified assumptions with other conflicts.
Fixes #85

fix(add): Allow optional build depednencies

---

README.md

docs: Link to related subcommands

---

src/manifest.rs

This is prep for inserting and upgrading requiring knowing what the
current manifests path is.

refactor: Consolidate mutations to LocalManifest

---

src/fetch.rs

Accidentally introduced at https://github.com/killercup/cargo-edit/pull/532#discussion_r744627152
@ordian FYI

Remove unnecessary index update

---

src/crate_name.rs
src/fetch.rs

refactor: Extract manifest loading logic

---

src/bin/set-version/version.rs

This matches relative version behavior.

fix(version): Handle build metadata for absolute versions

---

src/manifest.rs
tests/cmd/add/overwrite_rename_with_rename_noop.in/Cargo.toml
tests/cmd/add/overwrite_rename_with_rename_noop.out/Cargo.toml
tests/cmd/add/overwrite_rename_with_rename_noop.toml
tests/cmd/copy.sh
tests/cmd/rename.sh

fix(add): Allow double-add with --rename 

---

src/bin/add/args.rs
src/crate_name.rs
src/dependency.rs
src/manifest.rs
tests/cmd/add/git_rev.in
tests/cmd/add/git_rev.out/Cargo.toml
tests/cmd/add/git_rev.toml
tests/cmd/add/git_tag.in
tests/cmd/add/git_tag.out/Cargo.toml
tests/cmd/add/git_tag.toml
tests/cmd/add/overwrite_git_with_path.in/primary/Cargo.toml

feat(add): Git tag and rev support

---

src/bin/add/args.rs
src/bin/add/main.rs
tests/cmd/add/manifest_path_package.in/Cargo.toml
tests/cmd/add/manifest_path_package.in/dependency/Cargo.toml
tests/cmd/add/manifest_path_package.in/primary/Cargo.toml
tests/cmd/add/manifest_path_package.out/Cargo.toml
tests/cmd/add/manifest_path_package.out/dependency/Cargo.toml
tests/cmd/add/manifest_path_package.out/primary/Cargo.toml
tests/cmd/add/manifest_path_package.toml

This better matches cargo's behavior.

fix(add): Allow mixing --manifest-path with --package 

---

README.md
src/bin/add/args.rs
src/dependency.rs
tests/cmd/add/no_optional.in
tests/cmd/add/no_optional.out/Cargo.toml
tests/cmd/add/no_optional.toml
tests/cmd/add/overwrite_no_optional.in/Cargo.toml
tests/cmd/add/overwrite_no_optional.out/Cargo.toml
tests/cmd/add/overwrite_no_optional.toml
tests/cmd/add/overwrite_no_optional_with_optional.in/Cargo.toml
tests/cmd/add/overwrite_no_optional_with_optional.out/Cargo.toml
tests/cmd/add/overwrite_no_optional_with_optional.toml
tests/cmd/add/overwrite_optional.in/Cargo.toml
tests/cmd/add/overwrite_optional.out/Cargo.toml
tests/cmd/add/overwrite_optional.toml
tests/cmd/add/overwrite_optional_with_no_optional.in/Cargo.toml
tests/cmd/add/overwrite_optional_with_no_optional.out/Cargo.toml
tests/cmd/add/overwrite_optional_with_no_optional.toml

- On fresh add, the default is `--no-optional`.
- When overwriting without a flag, we preserve the existing value.
- In all other cases, we do what the flag says.
Fixes #298

fix(add): Allow disabling `optional = true`

---

src/bin/add/args.rs

We'll revert this as we get closer to merging into cargo.

fix(add): For now, only warn that inline-add is unstable

---

src/bin/add/main.rs
src/bin/rm/main.rs
src/bin/set-version/main.rs
src/bin/upgrade/main.rs
src/manifest.rs
tests/cmd/upgrade/dry_run.toml
tests/cmd/upgrade/dry_run_prerelease.toml

In looking at ways to simplify #613, I was driven nuts by the code organization, so I re did some things.  Technically, the old way was more optimal but I don't think the performance difference will matter.

refactor(upgrade): Make it easier to modify

---

src/manifest.rs

Currently, `get_version` returns a `toml_edit::Item`. However, all of `get_version`'s callers invoke `as_str` on the returned `Item`. By pushing the call to `as_str` into `get_version`, this change simplifies the callers.
Moreover, it is arguably an error if `as_str` returns `None`. However, none of `get_version`'s callers treat this siutation as an error. With this change, `get_version` itself returns an error if `as_str` returns `None`.
(These observations are a consequence of #613. But this change is not needed to implement #613.)

Make `get_version` return a string

---

README.md
src/bin/upgrade/main.rs
tests/cmd/upgrade/preserve_precision_major.in/Cargo.toml
tests/cmd/upgrade/preserve_precision_major.out/Cargo.toml
tests/cmd/upgrade/preserve_precision_major.toml
tests/cmd/upgrade/preserve_precision_minor.in/Cargo.toml
tests/cmd/upgrade/preserve_precision_minor.out/Cargo.toml
tests/cmd/upgrade/preserve_precision_minor.toml
tests/cmd/upgrade/preserve_precision_patch.in/Cargo.toml
tests/cmd/upgrade/preserve_precision_patch.out/Cargo.toml
tests/cmd/upgrade/preserve_precision_patch.toml

Add `--preserve-precision` flag to `cargo-upgrade`

---

crates/cargo-add/src/bin/cargo/cli.rs
crates/cargo-add/src/bin/cargo/commands/add.rs
crates/cargo-add/src/bin/cargo/commands/mod.rs
crates/cargo-add/src/bin/cargo/main.rs
crates/cargo-add/src/ops/cargo_add/dependency.rs
crates/cargo-add/tests/cmd/add/git_conflicts_registry.toml
crates/cargo-add/tests/cmd/add/invalid_inline_path_self.toml

This is prep for reusing clap code from cargo.

refactor: Move away from derive

---

Cargo.toml
crates/cargo-add/Cargo.toml
crates/cargo-add/src/bin/cargo/commands/add.rs
crates/cargo-add/src/ops/cargo_add/dependency.rs
crates/cargo-add/src/ops/cargo_add/fetch.rs
crates/cargo-add/src/ops/cargo_add/manifest.rs
crates/cargo-add/tests/cmd/add/add_normalized_name_external.toml
crates/cargo-add/tests/cmd/add/features.toml
crates/cargo-add/tests/cmd/add/features_empty.toml
crates/cargo-add/tests/cmd/add/features_multiple_occurrences.toml
crates/cargo-add/tests/cmd/add/features_preserve.toml
crates/cargo-add/tests/cmd/add/features_spaced_values.toml
crates/cargo-add/tests/cmd/add/features_unknown.toml
crates/cargo-add/tests/cmd/add/git_external.out/Cargo.toml
crates/cargo-add/tests/cmd/add/git_external.toml
crates/cargo-add/tests/cmd/add/invalid_git_external.toml
crates/cargo-add/tests/cmd/add/invalid_name_external.toml
crates/cargo-add/tests/cmd/add/list_features.toml
crates/cargo-add/tests/cmd/add/list_features_path.toml
crates/cargo-add/tests/cmd/add/overwrite_features.toml
crates/cargo-add/tests/cmd/add/overwrite_inline_features.toml
src/dependency.rs
src/fetch.rs
src/manifest.rs

This
- Cleans up printing of features
- Fixes crate name normalization
- Fixes some tests

chore: Updates from master

---

src/bin/add/add.rs

Unsure how I previously overlooked this.

fix(add): Walk all activated features

---

crates/cargo-add/src/bin/cargo/commands/add.rs

Unsure how I previously overlooked this.

fix(add): Walk all activated features 

---

crates/cargo-add/src/bin/cargo/commands/add.rs
crates/cargo-add/src/ops/cargo_add/crate_spec.rs
crates/cargo-add/src/ops/cargo_add/dependency.rs
crates/cargo-add/src/ops/cargo_add/fetch.rs
crates/cargo-add/src/ops/cargo_add/manifest.rs
crates/cargo-add/src/ops/cargo_add/mod.rs
crates/cargo-add/src/ops/cargo_add/registry.rs
crates/cargo-add/tests/cmd/add/git.toml
crates/cargo-add/tests/cmd/add/git_branch.toml
crates/cargo-add/tests/cmd/add/git_dev.toml
crates/cargo-add/tests/cmd/add/git_external.toml
crates/cargo-add/tests/cmd/add/git_rev.toml
crates/cargo-add/tests/cmd/add/git_tag.toml
crates/cargo-add/tests/cmd/add/inline_path.out/primary/Cargo.toml
crates/cargo-add/tests/cmd/add/overwrite_git_with_inline_path.out/primary/Cargo.toml
crates/cargo-add/tests/cmd/add/overwrite_version_with_git.toml
crates/cargo-add/tests/cmd/add/overwrite_version_with_inline_path.out/primary/Cargo.toml

Hoping this will help with using cargo's registry

refactor(add): Distinguish each primary source

---

crates/cargo-add/src/bin/cargo/commands/add.rs
crates/cargo-add/src/ops/cargo_add/dependency.rs
crates/cargo-add/tests/cmd/add/features_preserve.toml
crates/cargo-add/tests/cmd/add/overwrite_name_dev_noop.toml
crates/cargo-add/tests/cmd/add/overwrite_name_noop.toml
crates/cargo-add/tests/cmd/add/overwrite_rename_with_rename_noop.toml

Before when updating, we showed things as if we were adding new.  This will now show the user the merged state in some cases.
A future change will hopefully have it show merged in all cases.

fix(add): Show merged state to user

---

crates/cargo-add/src/bin/cargo/commands/add.rs
crates/cargo-add/src/ops/cargo_add/dependency.rs
crates/cargo-add/tests/cmd/add/overwrite_features.toml
crates/cargo-add/tests/cmd/add/overwrite_git_with_inline_path.toml
crates/cargo-add/tests/cmd/add/overwrite_inline_features.toml
crates/cargo-add/tests/cmd/add/overwrite_path_noop.toml
crates/cargo-add/tests/cmd/add/overwrite_path_with_version.toml
crates/cargo-add/tests/cmd/add/overwrite_version_with_git.toml
crates/cargo-add/tests/cmd/add/overwrite_version_with_inline_path.toml

This fixes several bugs where we only show the user what they've inputed and not the final state when merging.
This also helps define more clearly some of the semantics.

fix(add): Show the user final state

---

Cargo.lock
crates/cargo-add/Cargo.toml
crates/cargo-add/src/bin/cargo/commands/add.rs
crates/cargo-add/src/cargo/ops/cargo_add/dependency.rs
crates/cargo-add/src/cargo/ops/cargo_add/manifest.rs
crates/cargo-add/src/cargo/ops/cargo_add/mod.rs
crates/cargo-add/tests/snapshots/add/invalid_path.stderr
crates/cargo-add/tests/snapshots/add/path_inferred_name_conflicts_full_feature.in/Cargo.toml
crates/cargo-add/tests/snapshots/add/path_inferred_name_conflicts_full_feature.in/dependency/Cargo.toml
crates/cargo-add/tests/snapshots/add/path_inferred_name_conflicts_full_feature.in/optional/Cargo.toml
crates/cargo-add/tests/snapshots/add/path_inferred_name_conflicts_full_feature.in/primary/Cargo.toml
crates/cargo-add/tests/snapshots/add/path_inferred_name_conflicts_full_feature.out/Cargo.toml
crates/cargo-add/tests/snapshots/add/path_inferred_name_conflicts_full_feature.out/dependency/Cargo.toml
crates/cargo-add/tests/snapshots/add/path_inferred_name_conflicts_full_feature.out/primary/Cargo.toml
crates/cargo-add/tests/snapshots/add/path_inferred_name_conflicts_full_feature.stderr
crates/cargo-add/tests/snapshots/add/quiet.in
crates/cargo-add/tests/snapshots/add/quiet.out/Cargo.toml
crates/cargo-add/tests/testsuite/cargo_add.rs

I also came across normalize_path and figured I'd give it a try in case it lets us remove a dependenc

Latest round of feedback

---

README.md
src/bin/upgrade/upgrade.rs
tests/cmd/upgrade/skip_pinned.in/Cargo.toml
tests/cmd/upgrade/skip_pinned.out/Cargo.toml
tests/cmd/upgrade/skip_pinned.toml

cargo upgrade: Add --skip-pinned option

---

src/bin/upgrade/upgrade.rs
tests/cmd/upgrade/invalid_dep.toml

fix(upgrade): Report errors for invalid dependencies

---

README.md
src/bin/upgrade/upgrade.rs
tests/cmd/upgrade/locked.in/Cargo.toml
tests/cmd/upgrade/locked.out/Cargo.toml
tests/cmd/upgrade/locked.toml

feat(upgrade): Add --locked support

---

src/bin/rm/rm.rs
src/bin/set-version/set_version.rs
src/bin/upgrade/upgrade.rs

fix: Allow --manifest-path with -p

---

src/bin/rm/rm.rs
tests/cmd/rm/invalid_dep.toml
tests/cmd/rm/invalid_rm_target.toml
tests/cmd/rm/invalid_rm_target_dep.toml
tests/cmd/rm/invalid_section.toml
tests/cmd/rm/invalid_section_dep.toml

fix(rm): remove duplicate errors

---

.github/workflows/post-release.yml
.github/workflows/release-notes.py

chore(ci): Automatically create github releases

---

src/bin/upgrade/upgrade.rs

For now, we are just ignoring the lock file unless `--to-lockfile` is
specified.  Later if we add outdated support, we'll want to show lock
file status but it'll be optional in that case.
Fixes #745

fix(upgrade): Don't fail on no lockfile

---

crates/cargo-remove/src/bin/cargo/cli.rs
crates/cargo-remove/src/bin/cargo/commands/remove.rs

Make small changes in preparation for reworking the `exec` function.

Make cli args more like cargo

---

crates/cargo-remove/src/bin/cargo/commands/remove.rs
crates/cargo-remove/src/cargo/ops/cargo_remove/manifest.rs
crates/cargo-remove/src/cargo/ops/cargo_remove/mod.rs

As mentioned before, soon I will start merging in changes to `{dependency,manifest,metadata}.rs` from cargo/cargo add. 2378a8d is only a temporary change made to ease this transition.

Merge rm improve impl

---

src/bin/set-version/version.rs

This is more establishing the pattern than anything else.  We could use a lot more of these.

test(bump): Basic bump test

---

crates/cargo-remove/src/cargo/ops/cargo_remove/mod.rs

Use for loop instead of map iterator. Add FIXME comment describing suggested changes from #807.
I could remove the FIXME, but I sort of expect given how small this function is that someone will just bring it up if it's not pointed out. I can remove it though.

refactor(remove): clean up removal function

---

src/bin/set-version/set_version.rs
tests/cmd/set-version/ignore_dependent.toml
tests/cmd/set-version/set_absolute_version.toml
tests/cmd/set-version/set_relative_version.toml
tests/cmd/set-version/upgrade_compatible_dependency.toml
tests/cmd/set-version/upgrade_incompatible_dependency.toml
tests/cmd/set-version/upgrade_workspace.toml

This updates API calls and format of the output to be more like cargo

fix(version): Make consistent with cargo

---

README.md
src/bin/set-version/set_version.rs
src/lib.rs
src/manifest.rs
src/metadata.rs
tests/cargo-set-version/dry_run/in/Cargo.toml
tests/cargo-set-version/dry_run/mod.rs
tests/cargo-set-version/dry_run/out/Cargo.toml
tests/cargo-set-version/dry_run/stderr.log
tests/cargo-set-version/main.rs
tests/cargo-set-version/virtual_workspace_deps/in/Cargo.toml
tests/cargo-set-version/virtual_workspace_deps/in/dependency/Cargo.toml
tests/cargo-set-version/virtual_workspace_deps/in/primary/Cargo.toml
tests/cargo-set-version/virtual_workspace_deps/mod.rs
tests/cargo-set-version/virtual_workspace_deps/out/Cargo.toml
tests/cargo-set-version/virtual_workspace_deps/out/dependency/Cargo.toml
tests/cargo-set-version/virtual_workspace_deps/out/primary/Cargo.toml
tests/cargo-set-version/virtual_workspace_deps/stderr.log
tests/cargo-set-version/workspace_deps/in/Cargo.toml
tests/cargo-set-version/workspace_deps/in/dependency/Cargo.toml
tests/cargo-set-version/workspace_deps/mod.rs
tests/cargo-set-version/workspace_deps/out/Cargo.toml
tests/cargo-set-version/workspace_deps/out/dependency/Cargo.toml
tests/cargo-set-version/workspace_deps/stderr.log

- We were misattributing it to the root package, rather than the workspace
- We weren't supporting virtual workspaces

fix(version): Update `workspace.dependencies`

---

src/bin/add/main.rs
src/bin/rm/main.rs
src/bin/set-version/main.rs
src/bin/set-version/set_version.rs
src/bin/upgrade/main.rs
src/bin/upgrade/upgrade.rs
src/crate_spec.rs
src/dependency.rs
src/fetch.rs
src/manifest.rs
src/util.rs
src/version.rs

1) Removed a lifetime that was not needed.
2) Made writeln!(), format!() and eprintln!() more readable

Clippy fixes.

---

src/bin/upgrade/upgrade.rs
tests/cargo-upgrade/locked_dry_run/in/Cargo.toml
tests/cargo-upgrade/locked_dry_run/mod.rs
tests/cargo-upgrade/locked_dry_run/out/Cargo.toml
tests/cargo-upgrade/locked_dry_run/stderr.log
tests/cargo-upgrade/locked_dry_run/stdout.log
tests/cargo-upgrade/main.rs

fix(upgrade): Include --locked failure in dry-run

---

src/bin/set-version/errors.rs
src/manifest.rs
src/version.rs
tests/cargo-upgrade/invalid_manifest/stderr.log
tests/cargo-upgrade/invalid_workspace_root_manifest/stderr.log

Found with rust-lang/cargo#10554

fix: Correctly activate debug assertions

---

README.md

https://github.com/eopb/cargo-override
Related to #274

docs: include `cargo override` in list of related commands

---

Cargo.lock
Cargo.toml
src/bin/set-version/set_version.rs

chore: Remove unused deps

---

src/bin/upgrade/upgrade.rs
src/errors.rs
src/fetch.rs
src/index.rs
src/lib.rs

fix(upgrade): Don't silence network errors 

---

Cargo.lock
Cargo.toml
src/bin/upgrade/upgrade.rs
src/manifest.rs
src/metadata.rs
src/version.rs

- Update dependencies
- Fix warnings

chore(deps): update dependencies
